#pragma config(Motor,  port1,        0    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port2,        1    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,        2    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,        3    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,        4    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,        5    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,        6    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,        7    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,        8    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,       9    ,             tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#pragma autonomousDuration(45) // MAJ: We need to change that
#pragma userControlDuration(75) // MAJ: We need to change that.

#include "Vex_Competition_Includes.c"

int OFF = 0;

void movement()
//* ------------------------------------------------------------------ *//
//* Refresh motor information to activate and go in any direction value = f(x,y) *//
//* The robot can moves in any directions *//
//* params: none. *//
//* changes: get Axis 3 & 4 values and select values for wheel motors. *//
//* return: this function do not return anything. *//
//* ------------------------------------------------------------------ *//
{
	int x, y;
	x = vexRT[Ch4];
	y = vexRT[Ch3];
	if(x <= 5 && x >= -5)
	{
		x = 0;
	}
	if(y <= 5 && y >= -5)
	{
		y = 0;
	}
	motor[9] = (2*(-(x+y)));
	motor[0] = (2*(-(-x+y)));
	motor[2] = (2*(-(x-y)));
	motor[1] = (2*(x+y));

}

void allInOff()
//* ------------------------------------------------------------------ *//
//* Refresh motor information to deactivate value = OFF *//
//* param: none. *//
//* changes: array motor values equal global variable OFF. *//
//* return: this function do not return anything. *//
//* ------------------------------------------------------------------ *//
{
	for(int i=0;i<10;i++)
	{
		motor[i]=OFF;
	}
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
    allInOff();
}

void autonomousControl()
{

}


task usercontrol()
{
	while(1)
	{
		movement();
		if(vexRT[Btn7D] == 1)
		{
			motor[5] = 100;
			motor[6] = -100;
		}
		if(vexRT[Btn7U] == 1)
		{
			motor[5] = -100;
			motor[6] = 100;
		}
		if(vexRT[Btn8U] == 1)
		{
			motor[7] = -150;
		}
		if(vexRT[Btn8D] == 1)
		{
			motor[7] = 150;
		}
		if(vexRT[Btn5U] == 1)
		{
			motor[3] = 200;
			motor[4] = -200;
		}
		if(vexRT[Btn5D] == 1)
		{
			motor[3] = -200;
			motor[4] = 200;
		}
		if(vexRT[Btn8R] == 1)
		{
			motor[8] = 200;
		}
		if(vexRT[Btn8L] == 1)
		{
			motor[8] = -200;
		}
		sleep(100);
		allInOff();
	}

}

task autonomous()
{
    autonomousControl();
}
