#pragma config(Motor,  port1,        0    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port2,        1    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,        2    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,        3    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,        4    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,        5    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,        6    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,        7    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,        8    ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,       9    ,             tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15) // MAJ: We need to change that
#pragma userControlDuration(105) // : We need to change that.

#include "Vex_Competition_Includes.c"
#include "BasicFunctions.h"


task usercontrol()
{
	while(1)
	{
		movement();
		arm();

		if(vexRT[Btn5U] == 1)
		{
			motor[3] = 250;
			motor[4] = -250;
		}
		if(vexRT[Btn5D] == 1)
		{
			motor[3] = -250;
			motor[4] = 250
			;
		}
		if(vexRT[Btn6U] == 1)
		{
			motor[8] = 200;
		}
		if(vexRT[Btn6D] == 1)
		{
			motor[8] = -200;
		}
		if(vexRT[Btn8D] == 1)
		{
			motor[7] = 200;
		}
		if(vexRT[Btn8U] == 1)
		{
			motor[7] = -200;
		}
		sleep(100);
		allInOff();
	}

}

task autonomous()
{
    autonomousControl();
}
