#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait1Msec(2000);                // wait 2 seconds before exectuing following code
  bMotorReflected[port2] = true;  // reflects direction of motor on port 2

  while(true)                     // infinite loop:
  {
    writeDebugStream("%d", SensorValue(lineFollower)); // if the lineFollower sensor reads a value less than 950:
    wait10Msec(20);
    clearDebugStream();
  }
}
