#pragma config(Sensor, dgtl1,    lineFollower,   sensorQuadEncoder)
#pragma config(Sensor, dgtl2,    lineFollower2,   sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait1Msec(200);                // wait 2 seconds before exectuing following code
  SensorValue(lineFollower2)=0;
  SensorValue(lineFollower)=0;

  while(true)                     // infinite loop:
  {
    writeDebugStream("%d", SensorValue(lineFollower2)); // if the lineFollower sensor reads a value less than 950:
    wait10Msec(20);
    clearDebugStream();
  }
}
