#pragma config(Sensor, port5, dgt5,               sensorVexIQ_Distance)
#pragma config(Sensor, port6,  dgt6,               sensorVexIQ_Distance)
#pragma config(Sensor, port11, xAccel,               sensorVexIQ_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
  SensorType[in1] = sensorNone;
  wait1Msec(1000);
  //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[in8] = sensorGyro;
  wait1Msec(2000);

	while(1){
		writeDebugStream("%d", abs(SensorValue(in1)));
		wait10Msec(20);
		clearDebugStream();

	}
}
